### ISSUE TITLE
Refueling 

### ISSUE THREAD

**Issue by Neptune79** [4c65736975/manualRefueling#12]
### Version

1.0.0.3

### Game Version

Farming Simulator 22 (1.13.1.1)

### 👣 Steps to reproduce

Utilizing the fuel trailer included in the DEF pack on modhub - Pull Trailer next to tractor, step out and press R by default or the bound key for refueling. 

### ⭐️ Expected Behavior

The trailer to refuel the tractor. 

### ⛔️ Actual Behavior

The fuel starts/stop rapidly as if something is disconnected and does not refuel the equipment.

**Comment by 4c65736975** [comment]
> ### Version
> 1.0.0.3
> 
> ### Game Version
> Farming Simulator 22 (1.13.1.1)
> 
> ### 👣 Steps to reproduce
> Utilizing the fuel trailer included in the DEF pack on modhub - Pull Trailer next to tractor, step out and press R by default or the bound key for refueling.
> 
> ### ⭐️ Expected Behavior
> The trailer to refuel the tractor.
> 
> ### ⛔️ Actual Behavior
> The fuel starts/stop rapidly as if something is disconnected and does not refuel the equipment.

I couldn't reproduce this problem, everything works fine for me, are we talking about the FST990 trailer? Please check it on a clean save with only these two modifications and let me know.

**Comment by Neptune79** [comment]
Yes, the FST990. Odd thing, I took my game from the dedicated server and tried it single player. It works, no issues same mods and all enabled. So I'm not sure what the issue could be then.

**Comment by 4c65736975** [comment]
> Yes, the FST990. Odd thing, I took my game from the dedicated server and tried it single player. It works, no issues same mods and all enabled. So I'm not sure what the issue could be then.

Unfortunately, I didn't have the opportunity to test it on a dedicated server, only on a normal one

Could you please send me the server and client logs?

**Comment by Neptune79** [comment]
So I disabled the manual refueling mod and it appears to work via trailer now. I will try to downgrade to 1.0.2 and see if we still have this issue. If so, I will provide the server logs.

**Comment by Neptune79** [comment]
So appears downgrading it seems to of work. So I'm not sure if it's a mod conflict or what the issue is. All my mods come from mod hub.

**Comment by 4c65736975** [comment]
> So appears downgrading it seems to of work. So I'm not sure if it's a mod conflict or what the issue is. All my mods come from mod hub.

Does this happen only with this trailer or with all of them? I would be grateful if you could send me the server and client logs.

**Comment by Neptune79** [comment]
All of them even the default fuel trailer. Let me see if I can pull my logs.

**Comment by 4c65736975** [comment]
That's quite interesting.. Okay

**Comment by Neptune79** [comment]
[Client log.txt](https://github.com/VertexFloat/manualRefueling/files/14444254/Client.log.txt)
[Server log.txt](https://github.com/VertexFloat/manualRefueling/files/14444266/Server.log.txt)

**Comment by 4c65736975** [comment]
> All of them even the default fuel trailer. Let me see if I can pull my logs.

Okay, when I have access to another computer later, I'll check it and let you know.

**Comment by Neptune79** [comment]
Thanks!

**Comment by 4c65736975** [comment]
One more question, cause I understand that from buildings works fine?

**Comment by Neptune79** [comment]
Yes buildings work fine. I can even manually refuel the trailers. Just that when trying to refill a tractor from the trailer manually it doesn't work.

**Comment by 4c65736975** [comment]
> Yes buildings work fine. I can even manually refuel the trailers. Just that when trying to refill a tractor from the trailer manually it doesn't work.

The problem has been fixed, please download the latest version from github if you can and let me know if everything works properly
